baseURL = "https://empiler.constructions-incongrues.net"
enableGitInfo = true

title = 'Empiler'

[params]
  AuthorName = 'Constructions Incongrues'
  GitHubUser = 'constructions-incongrues'

[permalinks]
  audio-selecta = '/audio-selecta/:slug/'

[mediaTypes.'application/json']
  suffixes = ['json']

[outputFormats.JSON]
  mediaType = "application/json"
  isPlainText = true

[outputs]
  home = ['HTML']
  page = ['HTML', 'JSON', 'RSS']
