baseURL = "https://empiler.incongru.org"
enableGitInfo = true

title = "L'Ampoule des Sens"
subtitle = "La situation empile à chaque seconde"

[params]
  AuthorName = 'Constructions Incongrues'
  GitHubUser = 'constructions-incongrues'

[mediaTypes.'application/json']
  suffixes = ['json']

[outputFormats.JSON]
  mediaType = "application/json"
  isPlainText = true

[outputs]
  home = ['HTML']
  section = ['HTML', 'RSS', 'JSON']
  page = ['HTML', 'JSON', 'RSS']
