baseURL = "https://empilement.constructions-incongrues.net"
enableGitInfo = true

title = 'Empilements'

[params]
  AuthorName = 'Constructions Incongrues'
  GitHubUser = 'constructions-incongrues'

[permalinks]
  empilement = '/:slug/'

[frontmatter]
  date = [':git', ':default']

[outputs]
  home = ['HTML']
  empilement = ['HTML', 'RSS', 'JSON']
