baseURL = "https://empilement.constructions-incongrues.net"
enableGitInfo = true

title = 'Empilements'

[params]
  AuthorName = 'Constructions Incongrues'
  GitHubUser = 'constructions-incongrues'

[permalinks]
  empilement = '/empilement/:slug/'

[mediaTypes.'application/json']
  suffixes = ['json']

[outputs]
  home = ['HTML']
  empilement = ['HTML', 'RSS', 'JSON', 'YAML']
