baseURL = "https://conventicule.incongru.org"
enableGitInfo = true

title = "Conservatoire"

defaultContentLanguage = 'fr-fr'

[params]
  AuthorName = 'Constructions Incongrues'
  GitHubUser = 'constructions-incongrues'

[mediaTypes.'application/json']
  suffixes = ['json']

[outputFormats.JSON]
  mediaType = "application/json"
  isPlainText = true

[outputs]
  home = ['HTML']
  section = ['HTML', 'RSS', 'JSON']
  page = ['HTML', 'JSON', 'RSS']
