backend_local: true

backend:
  name: github
  repo: constructions-incongrues/empiler
  branch: main
  site_domain: 1a522206-9642-4c26-bac4-280770cfbff4
  auth_scope: repo
  open_authoring: true
  use_graphql: true
  squash_merges: true


media_folder: static/files
public_folder: /files

site_url: https://empiler.constructions-incongrues.net
show_preview_links: true
publish_mode: editorial_workflow

collections:
  - label: Audio Selecta
    name: audio-selecta
    folder: content/audio-selecta
    create: true
    slug: '{{title}}'
    preview_path: '{{slug}}'
    path: '{{slug}}/_index'
    extension: md
    format: json-frontmatter
    summary: "{{title}}"
    sortable_fields: [date, title]
    view_groups:
      - label: Year
        field: date
        # groups items based on the value matched by the pattern
        pattern: \d{4}
      - label: Curators
        field: curators

    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Release Date', name: 'date', widget: 'date' }

      - label: Curators
        name: curators
        widget: list
        fields:
          - label: Name
            name: name
            widget: string

      - { label: 'Description', name: 'description', widget: 'markdown', required: false }

      - label: Cover
        name: cover
        widget: image
        choose_url: false
        required: false

      - label: Tracks
        name: tracks
        widget: list
        fields:
          - label: Track
            name: track
            widget: object
            fields: 
              - label: Artist 
                name: artist
                widget: string
              - label: Title
                name: title
                widget: string
              - label: File
                name: file
                widget: file
                required: false
                choose_url: false

  - name: 'settings'
    label: 'Settings'
    delete: false 
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'Site Settings'
        file: 'data/settings.json'
        description: 'General Site Settings'
        fields:
          - { label: 'Global title', name: 'site_title', widget: 'string' }
