backend:
  name: github
  repo: constructions-incongrues/empilements

media_folder: 'assets/uploads'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }